---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: docker-cluster
servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.27.4-k3s1
registries: # define how registries should be created or used
  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.localhost`
    name: docker-registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"
